# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'capybara'
gem 'puma'
gem 'rerun'
gem 'rspec'
gem 'rubocop'
gem 'simplecov'
gem 'sinatra'
gem 'sinatra-reloader'
gem 'sinatra-contrib'

group :deployment do
  gem 'net-scp'
  gem 'ed25519'
  gem 'bcrypt_pbkdf'
  gem 'net-ssh'
end